version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: people_registration_db
    ports:
      - "5432:5432"
